services:

  qdrant-pivot2025:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant-pivot2025
    ports:
      - 6333:6333
      - 6334:6334
  #  configs:
  #    - source: qdrant_config
  #      target: /qdrant/config/production.yaml
    volumes:
      - ./data/qdrant-data:/qdrant_data
    
    networks:
      - pivot2025-nw

  ollama-pivot2025:
    image:  ollama/ollama
    container_name: ollama-pivot2025
    restart: unless-stopped
    volumes:
    - ./data/models/ollama:/root/.ollama
    ports:
    - 127.0.0.1:11434:11434
    environment:    
      - LLM_MODEL_VERSION="gemma3:4b" 
    healthcheck:
      test: ["CMD", "ollama", "run", "gemma3:4b"]

    networks:
      - pivot2025-nw

  ollama-embed-pivot2025:
    image:  ollama/ollama
    container_name: ollama-embed-pivot2025
    restart: unless-stopped
    volumes:
    - ./data/models/ollama-embed:/root/.ollama
    ports:
    - 127.0.0.1:11433:11433
    environment:    
      - LLM_MODEL_VERSION="nomic-embed-text"
      - OLLAMA_HOST="http://0.0.0.0:11433"
    healthcheck:
      test: ["CMD", "ollama", "run", "nomic-embed-text"]
    
    networks:
      - pivot2025-nw

networks:
  pivot2025-nw:
    external: true